#!/bin/bash

# Font download script for self-hosting Google Fonts
# Downloads WOFF2 files and creates optimized CSS

FONTS_DIR="public/fonts"
CSS_FILE="src/styles/self-hosted-fonts.css"

# Create directories
mkdir -p $FONTS_DIR
mkdir -p "$(dirname "$CSS_FILE")"

# Font families with their Google Fonts URLs
declare -A FONTS=(
  ["Bodoni+Moda"]="https://fonts.googleapis.com/css2?family=Bodoni+Moda:wght@400;500;600;700;800;900&display=swap"
  ["Cormorant+Garamond"]="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@300;400;500;600;700&display=swap"
  ["Crimson+Text"]="https://fonts.googleapis.com/css2?family=Crimson+Text:wght@400;600;700&display=swap"
  ["Fraunces"]="https://fonts.googleapis.com/css2?family=Fraunces:wght@300;400;500;600;700;800;900&display=swap"
  ["Inter"]="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800;900&display=swap"
  ["Source+Serif+4"]="https://fonts.googleapis.com/css2?family=Source+Serif+4:wght@300;400;500;600;700&display=swap"
  ["Space+Grotesk"]="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@300;400;500;600;700&display=swap"
  ["Unbounded"]="https://fonts.googleapis.com/css2?family=Unbounded:wght@300;400;500;600;700;800;900&display=swap"
)

# User agent for WOFF2 format
USER_AGENT="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"

echo "/* Self-hosted Google Fonts - Generated by POC-9 */" > $CSS_FILE
echo "/* Original fonts replaced to eliminate render-blocking requests */" >> $CSS_FILE
echo "" >> $CSS_FILE

for font_family in "${!FONTS[@]}"; do
  echo "Downloading $font_family..."
  
  # Get CSS from Google Fonts
  css_content=$(curl -s -H "User-Agent: $USER_AGENT" "${FONTS[$font_family]}")
  
  # Extract font URLs and download WOFF2 files
  echo "$css_content" | grep -o 'https://fonts.gstatic.com[^)]*\.woff2' | while read font_url; do
    # Extract filename
    filename=$(basename "$font_url")
    font_name_clean=$(echo "$font_family" | sed 's/+/-/g' | tr '[:upper:]' '[:lower:]')
    
    # Download font file
    curl -s -o "$FONTS_DIR/$filename" "$font_url"
    echo "Downloaded: $filename"
  done
  
  # Process CSS and update URLs
  updated_css=$(echo "$css_content" | sed "s|https://fonts.gstatic.com/s/[^/]*/v[0-9]*/|/fonts/|g")
  
  echo "/* $font_family */" >> $CSS_FILE
  echo "$updated_css" >> $CSS_FILE
  echo "" >> $CSS_FILE
done

echo "✅ All fonts downloaded to $FONTS_DIR"
echo "✅ CSS generated at $CSS_FILE"
echo ""
echo "Next steps:"
echo "1. Update daily-themes.json to use local font CSS"
echo "2. Add font preloading to MainLayout.astro"
echo "3. Test font loading performance"